Image component
prath-dev/PD-UI pull request #7
Opened 2022-02-19 15:18 UTC by prath-dev

2022-02-19 18:37 UTC, jeetbhalani15 approved these changes
good to go

2022-02-20 11:37 UTC, anurag-kkumarr requested changes
Else, It looks fine

2022-02-20 11:37 UTC, anurag-kkumarr commented on components/Images/images.css
> +    width: 35rem;
Use variable for colors and sizes.

2022-02-20 19:20 UTC, Vinayak-YB approved these changes
The code looks good to me.

2022-02-21 22:51 UTC, prath-dev commented
@anurag-kkumarr  : i will do  changes in second version of component

2022-02-21 22:51 UTC, merged